<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-30T18:44:03 IST" name="Default suite" finished-at="2024-05-30T18:44:15 IST" duration-ms="12415">
    <groups>
    </groups>
    <test started-at="2024-05-30T18:44:03 IST" name="Default test" finished-at="2024-05-30T18:44:15 IST" duration-ms="12415">
      <class name="com.synergyconnect.testcases.AdminSynergyConnect">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]" started-at="2024-05-30T18:44:03 IST" name="setup" finished-at="2024-05-30T18:44:06 IST" duration-ms="3370" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.synergyconnect.testcases.AdminSynergyConnect.verifyAddOrganization() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddOrganization()[pri:0, instance:com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]" started-at="2024-05-30T18:44:06 IST" name="verifyAddOrganization" finished-at="2024-05-30T18:44:09 IST" duration-ms="2197" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "com.synergyconnect.utilities.ExtentReportListener.getExtent()" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "com.synergyconnect.utilities.ExtentReportListener.getExtent()" is null
at com.synergyconnect.pageobject.LoginPage.enterUserid(LoginPage.java:36)
at com.synergyconnect.testcases.AdminSynergyConnect.verifyAddOrganization(AdminSynergyConnect.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddOrganization -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method)[pri:0, instance:com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]" started-at="2024-05-30T18:44:09 IST" name="tearDown" finished-at="2024-05-30T18:44:09 IST" duration-ms="319" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.synergyconnect.testcases.AdminSynergyConnect.verifyAddOrganization() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]" started-at="2024-05-30T18:44:09 IST" name="setup" finished-at="2024-05-30T18:44:11 IST" duration-ms="1688" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.synergyconnect.testcases.AdminSynergyConnect.verifyLoginisworking() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyLoginisworking()[pri:0, instance:com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]" started-at="2024-05-30T18:44:11 IST" name="verifyLoginisworking" finished-at="2024-05-30T18:44:15 IST" duration-ms="4525" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "com.synergyconnect.utilities.ExtentReportListener.getExtent()" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "com.synergyconnect.utilities.ExtentReportListener.getExtent()" is null
at com.synergyconnect.pageobject.LoginPage.enterUserid(LoginPage.java:36)
at com.synergyconnect.testcases.AdminSynergyConnect.verifyLoginisworking(AdminSynergyConnect.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginisworking -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method)[pri:0, instance:com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]" started-at="2024-05-30T18:44:15 IST" name="tearDown" finished-at="2024-05-30T18:44:15 IST" duration-ms="229" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.synergyconnect.testcases.AdminSynergyConnect.verifyLoginisworking() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="verifyAddLocation()[pri:1, instance:com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]" started-at="2024-05-30T18:44:15 IST" name="verifyAddLocation" finished-at="2024-05-30T18:44:15 IST" depends-on-methods="com.synergyconnect.testcases.AdminSynergyConnect.verifyLoginisworking" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.synergyconnect.testcases.AdminSynergyConnect.verifyAddLocation() on instance com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa depends on not successfully finished methods 
[com.synergyconnect.testcases.AdminSynergyConnect.verifyLoginisworking() on instance com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.synergyconnect.testcases.AdminSynergyConnect.verifyAddLocation() on instance com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa depends on not successfully finished methods 
[com.synergyconnect.testcases.AdminSynergyConnect.verifyLoginisworking() on instance com.synergyconnect.testcases.AdminSynergyConnect@5b7a5baa]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddLocation -->
      </class> <!-- com.synergyconnect.testcases.AdminSynergyConnect -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
